/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExtensionRouteRouteImport } from './routes/extension/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionPopupRouteImport } from './routes/extension/popup'
import { Route as AuthenticatedWellbeingRouteImport } from './routes/_authenticated/wellbeing'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCortexRouteImport } from './routes/_authenticated/cortex'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedChamberRouteImport } from './routes/_authenticated/chamber'
import { Route as AuthenticatedIntegrationsRouteRouteImport } from './routes/_authenticated/integrations/route'
import { Route as AuthenticatedIntegrationsSuggestionsRouteImport } from './routes/_authenticated/integrations/suggestions'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRouteRoute = ExtensionRouteRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionPopupRoute = ExtensionPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => ExtensionRouteRoute,
} as any)
const AuthenticatedWellbeingRoute = AuthenticatedWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCortexRoute = AuthenticatedCortexRouteImport.update({
  id: '/cortex',
  path: '/cortex',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChamberRoute = AuthenticatedChamberRouteImport.update({
  id: '/chamber',
  path: '/chamber',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRouteRoute =
  AuthenticatedIntegrationsRouteRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsSuggestionsRoute =
  AuthenticatedIntegrationsSuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => AuthenticatedIntegrationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integrations': typeof AuthenticatedIntegrationsRouteRouteWithChildren
  '/chamber': typeof AuthenticatedChamberRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/cortex': typeof AuthenticatedCortexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/extension/popup': typeof ExtensionPopupRoute
  '/integrations/suggestions': typeof AuthenticatedIntegrationsSuggestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integrations': typeof AuthenticatedIntegrationsRouteRouteWithChildren
  '/chamber': typeof AuthenticatedChamberRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/cortex': typeof AuthenticatedCortexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/extension/popup': typeof ExtensionPopupRoute
  '/integrations/suggestions': typeof AuthenticatedIntegrationsSuggestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/extension': typeof ExtensionRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRouteRouteWithChildren
  '/_authenticated/chamber': typeof AuthenticatedChamberRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/cortex': typeof AuthenticatedCortexRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wellbeing': typeof AuthenticatedWellbeingRoute
  '/extension/popup': typeof ExtensionPopupRoute
  '/_authenticated/integrations/suggestions': typeof AuthenticatedIntegrationsSuggestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extension'
    | '/auth'
    | '/integrations'
    | '/chamber'
    | '/coach'
    | '/community'
    | '/cortex'
    | '/dashboard'
    | '/domains'
    | '/mentor'
    | '/onboarding'
    | '/settings'
    | '/wellbeing'
    | '/extension/popup'
    | '/integrations/suggestions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extension'
    | '/auth'
    | '/integrations'
    | '/chamber'
    | '/coach'
    | '/community'
    | '/cortex'
    | '/dashboard'
    | '/domains'
    | '/mentor'
    | '/onboarding'
    | '/settings'
    | '/wellbeing'
    | '/extension/popup'
    | '/integrations/suggestions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/extension'
    | '/auth'
    | '/_authenticated/integrations'
    | '/_authenticated/chamber'
    | '/_authenticated/coach'
    | '/_authenticated/community'
    | '/_authenticated/cortex'
    | '/_authenticated/dashboard'
    | '/_authenticated/domains'
    | '/_authenticated/mentor'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/wellbeing'
    | '/extension/popup'
    | '/_authenticated/integrations/suggestions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ExtensionRouteRoute: typeof ExtensionRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/popup': {
      id: '/extension/popup'
      path: '/popup'
      fullPath: '/extension/popup'
      preLoaderRoute: typeof ExtensionPopupRouteImport
      parentRoute: typeof ExtensionRouteRoute
    }
    '/_authenticated/wellbeing': {
      id: '/_authenticated/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof AuthenticatedWellbeingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cortex': {
      id: '/_authenticated/cortex'
      path: '/cortex'
      fullPath: '/cortex'
      preLoaderRoute: typeof AuthenticatedCortexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamber': {
      id: '/_authenticated/chamber'
      path: '/chamber'
      fullPath: '/chamber'
      preLoaderRoute: typeof AuthenticatedChamberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations/suggestions': {
      id: '/_authenticated/integrations/suggestions'
      path: '/suggestions'
      fullPath: '/integrations/suggestions'
      preLoaderRoute: typeof AuthenticatedIntegrationsSuggestionsRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRouteRoute
    }
  }
}

interface AuthenticatedIntegrationsRouteRouteChildren {
  AuthenticatedIntegrationsSuggestionsRoute: typeof AuthenticatedIntegrationsSuggestionsRoute
}

const AuthenticatedIntegrationsRouteRouteChildren: AuthenticatedIntegrationsRouteRouteChildren =
  {
    AuthenticatedIntegrationsSuggestionsRoute:
      AuthenticatedIntegrationsSuggestionsRoute,
  }

const AuthenticatedIntegrationsRouteRouteWithChildren =
  AuthenticatedIntegrationsRouteRoute._addFileChildren(
    AuthenticatedIntegrationsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIntegrationsRouteRoute: typeof AuthenticatedIntegrationsRouteRouteWithChildren
  AuthenticatedChamberRoute: typeof AuthenticatedChamberRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedCortexRoute: typeof AuthenticatedCortexRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWellbeingRoute: typeof AuthenticatedWellbeingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIntegrationsRouteRoute:
    AuthenticatedIntegrationsRouteRouteWithChildren,
  AuthenticatedChamberRoute: AuthenticatedChamberRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedCortexRoute: AuthenticatedCortexRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWellbeingRoute: AuthenticatedWellbeingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ExtensionRouteRouteChildren {
  ExtensionPopupRoute: typeof ExtensionPopupRoute
}

const ExtensionRouteRouteChildren: ExtensionRouteRouteChildren = {
  ExtensionPopupRoute: ExtensionPopupRoute,
}

const ExtensionRouteRouteWithChildren = ExtensionRouteRoute._addFileChildren(
  ExtensionRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ExtensionRouteRoute: ExtensionRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
